// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        // Tests and some desktop targets use these; same web project config is fine for class/dev.
        return web;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzGRG5iKNfPzIbcfA9UX6WpDPhyqzXy7g',
    appId: '1:1052064859280:android:c83777b1d1513c38d30415',
    messagingSenderId: '1052064859280',
    projectId: 'mad-vibz-project',
    storageBucket: 'mad-vibz-project.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLBSAjFD7Gl8t6ipFLhhryUC-fAtRIYAk',
    appId: '1:812698514265:web:1cbe36add6771201fcd248',
    messagingSenderId: '812698514265',
    projectId: 'mad-vibez',
    authDomain: 'mad-vibez.firebaseapp.com',
    storageBucket: 'mad-vibez.firebasestorage.app',
  );

}